name: My CFW Builder
on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Start Compiling CFW
        run: pip3 install pyCrypto && echo Starting && docker build $(pwd) && docker run python3 castify.py && docker run make
