name: My CFW Builder
on: [push, pull_request]

jobs:
  build:
    name: Make The Custom Firmware
    runs-on: ubuntu-20.04
    container: devkitpro/devkitarm:20210622
 
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Make The Custom Firmware
      run: |
        apt-get update -y && apt-get install --no-install-recommends -y python3-crypto && make -j$(nproc)
    - name: Upload The Patcher To Download
      uses: actions/upload-artifact@v2
      with: 
        name: patcher download
        path: |
         /__w/Martini/Martini/build
