name: My CFW Builder
on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Start Compiling CFW
        run: wget https://github.com/SmmServer/FakeOnlineFiles/blob/master/otp.bin && cd scripts && python3 otpkey.py && echo extracted keys && echo Done #docker build && docker run sed s/B5XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/${DEFINITELY_LEGAL}/g -i castify.py && docker run sed s/91XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/${DO_THEY_EVEN_CARE}/g -i castify.py && docker run make
